### ISSUE TITLE
Update build process for release

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#2544]
- [x] Run composer update in an optimized fashion. Related:  #2447
- [x]  Only copy the build JavaScript for clients, remove webpack config from build Related:  #2444 #2167
- [x]  Remove docker config and related files Related: #2531 #2530
- [x] Create SVN tag programmatically #1320

**Comment by Shelob9** [comment]
Close via 9748d25
